version: '3.5'
services:
  fourleft_frontend:
    build: .
    ports:
      - target: 80
        published: 9080
        protocol: tcp
        mode: host
    restart: always
    container_name: fourleft_frontend

networks:
  default:
    name: veevi

