spring:
  application:
    name: backend-wrc
  config:
    import: "optional:configserver:"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000
  datasource:
      driver-class-name: org.postgresql.Driver
server:
  port: 8083