version: '3.5'
services:
  fourleft-reverse-proxy:
    build: devops/reverse-proxy
    container_name: fourleft-reverse-proxy
    restart: always
    environment:
      - VIRTUAL_HOST=fourleft.io
      - LETSENCRYPT_HOST=fourleft.io
networks:
  default:
    name: veevi