version: '3.5'
services:
  fourleft_discord:
    build: .
    container_name: fourleft_discord
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://host.docker.internal:8888
    depends_on:
      - db.fourleft_discord
  db.fourleft_discord:
    container_name: db.fourleft_discord
    image: postgres
    volumes:
      - pgdatafourleftdiscord:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  pgdatafourleftdiscord:
networks:
  default:
    name: veevi