version: '3.5'
services:
  db.local.rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /mnt/docker-data/rabbitmq:/var/lib/rabbitmq