-- Repeatable seed of track aliases derivable from the game files. GENERATED —
-- do not edit by hand; regenerate with tools/generate_track_alias_seed.py
-- (see its docstring for the full recipe) and commit the result.
--
-- Live telemetry writes "<localized location> <localized variant label>" into a
-- 32-UTF-16-unit field (hence the truncated entries); labels come from the
-- TRACK_*_SHORT locres keys with per-key English fallback, so most strings mix
-- languages. Older agents report the raw variant key itself. Also includes
-- 6 hand-curated entries for observed translation-mod strings; new mod
-- strings need admin assignment (or add them to MANUAL_ALIASES and
-- regenerate). 12 composition(s) the game emits identically for more than
-- one stage (e.g. "Alsace Forêt") are dropped on purpose and must stay
-- unassigned — assigning either variant would misbind the other's sessions.
--
-- Upsert policy: insert unknown aliases pre-assigned, fill variant_id on
-- existing unassigned rows, never touch an alias an admin already assigned.

INSERT INTO track_alias (id, raw_name, variant_id, created_at)
SELECT gen_random_uuid(), v.alias, var.id, now()
FROM (VALUES
    ('Alsace Col du petit Ballon', 'AlsaceS2MunsterShort2Reverse'),
    ('Alsace Descente', 'AlsaceS2MunsterFullReverse'),
    ('Alsace Forêt de Munster', 'AlsaceS2MunsterShort1Reverse'),
    ('Alsace Forêt de Saverne', 'AlsaceS4SaverneFullForward'),
    ('Alsace La Mossig', 'AlsaceS4SaverneShort1Reverse'),
    ('Alsace La traversée de La Mossig', 'AlsaceS4SaverneShort1Reverse'),
    ('Alsace Luttenbach', 'AlsaceS2MunsterShort1Forward'),
    ('Alsace Luttenbach près Munster', 'AlsaceS2MunsterShort1Forward'),
    ('Alsace Montée', 'AlsaceS2MunsterFullForward'),
    ('Alsace Obersteigen', 'AlsaceS4SaverneShort1Forward'),
    ('Alsace Petit Ballon', 'AlsaceS2MunsterShort2Reverse'),
    ('Alsace Sommet', 'AlsaceS2MunsterShort2Forward'),
    ('Alsace Sommet de Munster ', 'AlsaceS2MunsterShort2Forward'),
    ('Alsace Steigenbach', 'AlsaceS4SaverneFullReverse'),
    ('Alsace Vallée de Munster Descent', 'AlsaceS2MunsterFullReverse'),
    ('Alsace Vallée de Munster Montée', 'AlsaceS2MunsterFullForward'),
    ('AlsaceS2MunsterFullForward', 'AlsaceS2MunsterFullForward'),
    ('AlsaceS2MunsterFullReverse', 'AlsaceS2MunsterFullReverse'),
    ('AlsaceS2MunsterShort1Forward', 'AlsaceS2MunsterShort1Forward'),
    ('AlsaceS2MunsterShort1Reverse', 'AlsaceS2MunsterShort1Reverse'),
    ('AlsaceS2MunsterShort2Forward', 'AlsaceS2MunsterShort2Forward'),
    ('AlsaceS2MunsterShort2Reverse', 'AlsaceS2MunsterShort2Reverse'),
    ('AlsaceS4SaverneFullForward', 'AlsaceS4SaverneFullForward'),
    ('AlsaceS4SaverneFullReverse', 'AlsaceS4SaverneFullReverse'),
    ('AlsaceS4SaverneShort1Forward', 'AlsaceS4SaverneShort1Forward'),
    ('AlsaceS4SaverneShort1Reverse', 'AlsaceS4SaverneShort1Reverse'),
    ('Alsacia Col du petit Ballon', 'AlsaceS2MunsterShort2Reverse'),
    ('Alsacia Descente', 'AlsaceS2MunsterFullReverse'),
    ('Alsacia Forêt de Munster', 'AlsaceS2MunsterShort1Reverse'),
    ('Alsacia Forêt de Saverne', 'AlsaceS4SaverneFullForward'),
    ('Alsacia La Mossig', 'AlsaceS4SaverneShort1Reverse'),
    ('Alsacia La traversée de La Mossi', 'AlsaceS4SaverneShort1Reverse'),
    ('Alsacia Luttenbach', 'AlsaceS2MunsterShort1Forward'),
    ('Alsacia Luttenbach près Munster', 'AlsaceS2MunsterShort1Forward'),
    ('Alsacia Montée', 'AlsaceS2MunsterFullForward'),
    ('Alsacia Obersteigen', 'AlsaceS4SaverneShort1Forward'),
    ('Alsacia Petit Ballon', 'AlsaceS2MunsterShort2Reverse'),
    ('Alsacia Sommet', 'AlsaceS2MunsterShort2Forward'),
    ('Alsacia Sommet de Munster ', 'AlsaceS2MunsterShort2Forward'),
    ('Alsacia Steigenbach', 'AlsaceS4SaverneFullReverse'),
    ('Alsacia Vallée de Munster Descen', 'AlsaceS2MunsterFullReverse'),
    ('Alsacia Vallée de Munster Montée', 'AlsaceS2MunsterFullForward'),
    ('Alsazia Col du petit Ballon', 'AlsaceS2MunsterShort2Reverse'),
    ('Alsazia Descente', 'AlsaceS2MunsterFullReverse'),
    ('Alsazia Forêt de Munster', 'AlsaceS2MunsterShort1Reverse'),
    ('Alsazia Forêt de Saverne', 'AlsaceS4SaverneFullForward'),
    ('Alsazia La Mossig', 'AlsaceS4SaverneShort1Reverse'),
    ('Alsazia La traversée de La Mossi', 'AlsaceS4SaverneShort1Reverse'),
    ('Alsazia Luttenbach', 'AlsaceS2MunsterShort1Forward'),
    ('Alsazia Luttenbach-près-Munster', 'AlsaceS2MunsterShort1Forward'),
    ('Alsazia Montée', 'AlsaceS2MunsterFullForward'),
    ('Alsazia Obersteigen', 'AlsaceS4SaverneShort1Forward'),
    ('Alsazia Petit Ballon', 'AlsaceS2MunsterShort2Reverse'),
    ('Alsazia Sommet', 'AlsaceS2MunsterShort2Forward'),
    ('Alsazia Sommet de Munster ', 'AlsaceS2MunsterShort2Forward'),
    ('Alsazia Steigenbach', 'AlsaceS4SaverneFullReverse'),
    ('Alsazia Vallée de Munster Descen', 'AlsaceS2MunsterFullReverse'),
    ('Alsazia Vallée de Munster Montée', 'AlsaceS2MunsterFullForward'),
    ('Circuit de Livigno Livigno : inv', 'LivignoTestTrack01FullReverse'),
    ('Circuito de Livigno Principal in', 'LivignoTestTrack01FullReverse'),
    ('Circuito di Livigno Principale S', 'LivignoTestTrack01FullReverse'),
    ('Gales Afon Bidno', 'WelesS4HafrenSouthFullForward'),
    ('Gales Afon Bidno - Severn', 'WelesS4HafrenSouthFullForward'),
    ('Gales Afon Biga', 'WelesS3HafrenNorthFullReverse'),
    ('Gales Afon Biga - Banc Gwyn', 'WelesS3HafrenNorthCut2Reverse'),
    ('Gales Afon Biga - Cwmbiga', 'WelesS3HafrenNorthFullReverse'),
    ('Gales Banc Gwyn', 'WelesS3HafrenNorthCut2Forward'),
    ('Gales Banc Gwyn - Afon Biga', 'WelesS3HafrenNorthCut2Forward'),
    ('Gales Bosque de Hafren', 'WelesS3HafrenNorthCut1Forward'),
    ('Gales Cwmbiga', 'WelesS3HafrenNorthFullForward'),
    ('Gales Cwmbiga - Afon Biga', 'WelesS3HafrenNorthFullForward'),
    ('Gales Cwmbiga - Fedw Fain', 'WelesS3HafrenNorthCut1Forward'),
    ('Gales Fedw Fain', 'WelesS3HafrenNorthCut1Reverse'),
    ('Gales Fedw Fain - Cwmbiga', 'WelesS3HafrenNorthCut1Reverse'),
    ('Gales Ospreys', 'WelesS3HafrenNorthCut2Reverse'),
    ('Gales Severn', 'WelesS4HafrenSouthFullReverse'),
    ('Gales Severn - Afon Bidno', 'WelesS4HafrenSouthFullReverse'),
    ('Galles Afon Bidno', 'WelesS4HafrenSouthFullForward'),
    ('Galles Afon Bidno - Severn', 'WelesS4HafrenSouthFullForward'),
    ('Galles Afon Biga', 'WelesS3HafrenNorthFullReverse'),
    ('Galles Afon Biga - Banc Gwyn', 'WelesS3HafrenNorthCut2Reverse'),
    ('Galles Afon Biga - Cwmbiga', 'WelesS3HafrenNorthFullReverse'),
    ('Galles Banc Gwyn', 'WelesS3HafrenNorthCut2Forward'),
    ('Galles Banc Gwyn - Afon Biga', 'WelesS3HafrenNorthCut2Forward'),
    ('Galles Cwmbiga', 'WelesS3HafrenNorthFullForward'),
    ('Galles Cwmbiga - Afon Biga', 'WelesS3HafrenNorthFullForward'),
    ('Galles Cwmbiga - Fedw Fain', 'WelesS3HafrenNorthCut1Forward'),
    ('Galles Fedw Fain', 'WelesS3HafrenNorthCut1Reverse'),
    ('Galles Fedw Fain - Cwmbiga', 'WelesS3HafrenNorthCut1Reverse'),
    ('Galles Foresta di Hafren', 'WelesS3HafrenNorthCut1Forward'),
    ('Galles Ospreys', 'WelesS3HafrenNorthCut2Reverse'),
    ('Galles Severn', 'WelesS4HafrenSouthFullReverse'),
    ('Galles Severn - Afon Bidno', 'WelesS4HafrenSouthFullReverse'),
    ('Grecia Aghii Theodori', 'GreeceS4LoutrakiCut2Forward'),
    ('Grecia Aghii Theodori - Loutraki', 'GreeceS4LoutrakiFullReverse'),
    ('Grecia Aghii Theodori al contrar', 'GreeceS4LoutrakiCut2Reverse'),
    ('Grecia Aghii Theodori inverso', 'GreeceS4LoutrakiCut2Reverse'),
    ('Grecia Elatia', 'GreeceS3ElatiaCut1Forward'),
    ('Grecia Elatia - Zeli', 'GreeceS3ElatiaFullForward'),
    ('Grecia Elatia al contrario', 'GreeceS3ElatiaCut1Reverse'),
    ('Grecia Elatia inverso', 'GreeceS3ElatiaCut1Reverse'),
    ('Grecia Loutraki - Aghii Theodori', 'GreeceS4LoutrakiFullForward'),
    ('Grecia New Loutraki', 'GreeceS4LoutrakiCut1Forward'),
    ('Grecia New Loutraki al contrario', 'GreeceS4LoutrakiCut1Reverse'),
    ('Grecia Nuevo Loutraki', 'GreeceS4LoutrakiCut1Forward'),
    ('Grecia Nuevo Loutraki inverso', 'GreeceS4LoutrakiCut1Reverse'),
    ('Grecia Zeli', 'GreeceS3ElatiaCut2Forward'),
    ('Grecia Zeli - Elatia', 'GreeceS3ElatiaFullReverse'),
    ('Grecia Zeli Inversa', 'GreeceS3ElatiaCut2Reverse'),
    ('Grecia Zeli inverso', 'GreeceS3ElatiaCut2Reverse'),
    ('Greece Aghii Theodori', 'GreeceS4LoutrakiCut2Forward'),
    ('Greece Aghii Theodori - Loutraki', 'GreeceS4LoutrakiFullReverse'),
    ('Greece Aghii Theodori Reverse', 'GreeceS4LoutrakiCut2Reverse'),
    ('Greece Elatia', 'GreeceS3ElatiaCut1Forward'),
    ('Greece Elatia - Zeli', 'GreeceS3ElatiaFullForward'),
    ('Greece Elatia Reverse', 'GreeceS3ElatiaCut1Reverse'),
    ('Greece Loutraki - Aghii Theodori', 'GreeceS4LoutrakiFullForward'),
    ('Greece New Loutraki', 'GreeceS4LoutrakiCut1Forward'),
    ('Greece New Loutraki Reverse', 'GreeceS4LoutrakiCut1Reverse'),
    ('Greece Zeli', 'GreeceS3ElatiaCut2Forward'),
    ('Greece Zeli - Elatia', 'GreeceS3ElatiaFullReverse'),
    ('Greece Zeli Reverse', 'GreeceS3ElatiaCut2Reverse'),
    ('GreeceS3ElatiaCut1Forward', 'GreeceS3ElatiaCut1Forward'),
    ('GreeceS3ElatiaCut1Reverse', 'GreeceS3ElatiaCut1Reverse'),
    ('GreeceS3ElatiaCut2Forward', 'GreeceS3ElatiaCut2Forward'),
    ('GreeceS3ElatiaCut2Reverse', 'GreeceS3ElatiaCut2Reverse'),
    ('GreeceS3ElatiaFullForward', 'GreeceS3ElatiaFullForward'),
    ('GreeceS3ElatiaFullReverse', 'GreeceS3ElatiaFullReverse'),
    ('GreeceS4LoutrakiCut1Forward', 'GreeceS4LoutrakiCut1Forward'),
    ('GreeceS4LoutrakiCut1Reverse', 'GreeceS4LoutrakiCut1Reverse'),
    ('GreeceS4LoutrakiCut2Forward', 'GreeceS4LoutrakiCut2Forward'),
    ('GreeceS4LoutrakiCut2Reverse', 'GreeceS4LoutrakiCut2Reverse'),
    ('GreeceS4LoutrakiFullForward', 'GreeceS4LoutrakiFullForward'),
    ('GreeceS4LoutrakiFullReverse', 'GreeceS4LoutrakiFullReverse'),
    ('Griechenland Aghii Theodori', 'GreeceS4LoutrakiCut2Forward'),
    ('Griechenland Aghii Theodori - Lo', 'GreeceS4LoutrakiFullReverse'),
    ('Griechenland Aghii Theodori Rück', 'GreeceS4LoutrakiCut2Reverse'),
    ('Griechenland Elatia', 'GreeceS3ElatiaCut1Forward'),
    ('Griechenland Elatia - Zeli', 'GreeceS3ElatiaFullForward'),
    ('Griechenland Elatia Rückwärts', 'GreeceS3ElatiaCut1Reverse'),
    ('Griechenland Loutraki - Aghii Th', 'GreeceS4LoutrakiFullForward'),
    ('Griechenland Neues Loutraki', 'GreeceS4LoutrakiCut1Forward'),
    ('Griechenland Neues Loutraki Rück', 'GreeceS4LoutrakiCut1Reverse'),
    ('Griechenland Zeli', 'GreeceS3ElatiaCut2Forward'),
    ('Griechenland Zeli - Elatia', 'GreeceS3ElatiaFullReverse'),
    ('Griechenland Zeli Rückwärts', 'GreeceS3ElatiaCut2Reverse'),
    ('Grèce Aghii Theodori', 'GreeceS4LoutrakiCut2Forward'),
    ('Grèce Aghii Theodori - Loutraki', 'GreeceS4LoutrakiFullReverse'),
    ('Grèce Aghii Theodori inversé', 'GreeceS4LoutrakiCut2Reverse'),
    ('Grèce Elatia', 'GreeceS3ElatiaCut1Forward'),
    ('Grèce Elatia - Zeli', 'GreeceS3ElatiaFullForward'),
    ('Grèce Elatia inversé', 'GreeceS3ElatiaCut1Reverse'),
    ('Grèce Loutraki - Aghii Theodori', 'GreeceS4LoutrakiFullForward'),
    ('Grèce Nouveau Loutraki', 'GreeceS4LoutrakiCut1Forward'),
    ('Grèce Nouveau Loutraki inversé', 'GreeceS4LoutrakiCut1Reverse'),
    ('Grèce Zeli', 'GreeceS3ElatiaCut2Forward'),
    ('Grèce Zeli - Elatia', 'GreeceS3ElatiaFullReverse'),
    ('Grèce Zeli inversé', 'GreeceS3ElatiaCut2Reverse'),
    ('Grécia Aghii Theodori', 'GreeceS4LoutrakiCut2Forward'),
    ('Grécia Aghii Theodori (Inverso)', 'GreeceS4LoutrakiCut2Reverse'),
    ('Grécia Elatia', 'GreeceS3ElatiaCut1Forward'),
    ('Grécia New Loutraki', 'GreeceS4LoutrakiCut1Forward'),
    ('Grécia Zeli', 'GreeceS3ElatiaCut2Forward'),
    ('Grécia Zeli - Elatia', 'GreeceS3ElatiaFullReverse'),
    ('Livigno Circuit Main Circuit', 'LivignoTestTrack01FullForward'),
    ('Livigno Circuit Main Circuit Rev', 'LivignoTestTrack01FullReverse'),
    ('Livigno Circuit Main Reverse', 'LivignoTestTrack01FullReverse'),
    ('Livigno-Strecke Hauptstrecke', 'LivignoTestTrack01FullForward'),
    ('Livigno-Strecke Hauptstrecke in ', 'LivignoTestTrack01FullReverse'),
    ('LivignoTestTrack01FullForward', 'LivignoTestTrack01FullForward'),
    ('LivignoTestTrack01FullReverse', 'LivignoTestTrack01FullReverse'),
    ('Monte Carlo La Bollène', 'MonteCarloS1BolleneFullForward'),
    ('Monte Carlo Mézien - Sisteron', 'MonteCarloS2SisteronCut1Reverse'),
    ('Monte Carlo Mézien - St. Geniez', 'MonteCarloS2SisteronCut2Forward'),
    ('Monte Carlo Peïra Cava', 'MonteCarloS1BolleneFullReverse'),
    ('Monte Carlo Peïra Cava - La Boll', 'MonteCarloS1BolleneFullReverse'),
    ('Monte Carlo Peïra Cava - Turini', 'MonteCarloS1BolleneCut2Reverse'),
    ('Monte Carlo Peïra Cava – La Boll', 'MonteCarloS1BolleneFullReverse'),
    ('Monte Carlo Peïra Cava – Turini', 'MonteCarloS1BolleneCut2Reverse'),
    ('Monte Carlo Pra d''Alart', 'MonteCarloS1BolleneCut3Forward'),
    ('Monte Carlo Sisteron - Mézien', 'MonteCarloS2SisteronCut1Forward'),
    ('Monte Carlo Sisteron - St. Genie', 'MonteCarloS2SisteronFullForward'),
    ('Monte Carlo Sommet de Turini', 'MonteCarloS1BolleneCut3Reverse'),
    ('Monte Carlo St. Geniez - Mézien', 'MonteCarloS2SisteronCut2Reverse'),
    ('Monte Carlo St. Geniez - Sistero', 'MonteCarloS2SisteronFullReverse'),
    ('Monte Carlo Turini - La Bollène-', 'MonteCarloS1BolleneCut1Reverse'),
    ('Monte Carlo Turini - Peïra Cava', 'MonteCarloS1BolleneCut2Forward'),
    ('Monte Carlo Turini Descente', 'MonteCarloS1BolleneCut1Reverse'),
    ('Monte Carlo Turini Montée', 'MonteCarloS1BolleneCut1Forward'),
    ('Monte Carlo Turini – La Bollène-', 'MonteCarloS1BolleneCut1Reverse'),
    ('Monte Carlo Turini –Peïra Cava', 'MonteCarloS1BolleneCut2Forward'),
    ('Monte-Carlo La Bollène', 'MonteCarloS1BolleneFullForward'),
    ('Monte-Carlo Mézien - Sisteron', 'MonteCarloS2SisteronCut1Reverse'),
    ('Monte-Carlo Mézien - St. Geniez', 'MonteCarloS2SisteronCut2Forward'),
    ('Monte-Carlo Peïra Cava', 'MonteCarloS1BolleneFullReverse'),
    ('Monte-Carlo Peïra Cava - La Boll', 'MonteCarloS1BolleneFullReverse'),
    ('Monte-Carlo Peïra Cava - Turini', 'MonteCarloS1BolleneCut2Reverse'),
    ('Monte-Carlo Pra d''Alart', 'MonteCarloS1BolleneCut3Forward'),
    ('Monte-Carlo Sisteron - Mézien', 'MonteCarloS2SisteronCut1Forward'),
    ('Monte-Carlo Sisteron - St. Genie', 'MonteCarloS2SisteronFullForward'),
    ('Monte-Carlo Sommet de Turini', 'MonteCarloS1BolleneCut3Reverse'),
    ('Monte-Carlo St. Geniez - Mézien', 'MonteCarloS2SisteronCut2Reverse'),
    ('Monte-Carlo St. Geniez - Sistero', 'MonteCarloS2SisteronFullReverse'),
    ('Monte-Carlo Turini - La Bollène-', 'MonteCarloS1BolleneCut1Reverse'),
    ('Monte-Carlo Turini - Peïra Cava', 'MonteCarloS1BolleneCut2Forward'),
    ('Monte-Carlo Turini Descente', 'MonteCarloS1BolleneCut1Reverse'),
    ('Monte-Carlo Turini Montée', 'MonteCarloS1BolleneCut1Forward'),
    ('MonteCarloS1BolleneCut1Forward', 'MonteCarloS1BolleneCut1Forward'),
    ('MonteCarloS1BolleneCut1Reverse', 'MonteCarloS1BolleneCut1Reverse'),
    ('MonteCarloS1BolleneCut2Forward', 'MonteCarloS1BolleneCut2Forward'),
    ('MonteCarloS1BolleneCut2Reverse', 'MonteCarloS1BolleneCut2Reverse'),
    ('MonteCarloS1BolleneCut3Forward', 'MonteCarloS1BolleneCut3Forward'),
    ('MonteCarloS1BolleneCut3Reverse', 'MonteCarloS1BolleneCut3Reverse'),
    ('MonteCarloS1BolleneFullForward', 'MonteCarloS1BolleneFullForward'),
    ('MonteCarloS1BolleneFullReverse', 'MonteCarloS1BolleneFullReverse'),
    ('MonteCarloS2SisteronCut1Forward', 'MonteCarloS2SisteronCut1Forward'),
    ('MonteCarloS2SisteronCut1Reverse', 'MonteCarloS2SisteronCut1Reverse'),
    ('MonteCarloS2SisteronCut2Forward', 'MonteCarloS2SisteronCut2Forward'),
    ('MonteCarloS2SisteronCut2Reverse', 'MonteCarloS2SisteronCut2Reverse'),
    ('MonteCarloS2SisteronFullForward', 'MonteCarloS2SisteronFullForward'),
    ('MonteCarloS2SisteronFullReverse', 'MonteCarloS2SisteronFullReverse'),
    ('Montecarlo La Bollène', 'MonteCarloS1BolleneFullForward'),
    ('Montecarlo Mézien - Sisteron', 'MonteCarloS2SisteronCut1Reverse'),
    ('Montecarlo Mézien - St. Geniez', 'MonteCarloS2SisteronCut2Forward'),
    ('Montecarlo Peïra Cava', 'MonteCarloS1BolleneFullReverse'),
    ('Montecarlo Peïra Cava - La Bollè', 'MonteCarloS1BolleneFullReverse'),
    ('Montecarlo Peïra Cava - Turini', 'MonteCarloS1BolleneCut2Reverse'),
    ('Montecarlo Pra d''Alart', 'MonteCarloS1BolleneCut3Forward'),
    ('Montecarlo Sisteron - Mézien', 'MonteCarloS2SisteronCut1Forward'),
    ('Montecarlo Sisteron - St. Geniez', 'MonteCarloS2SisteronFullForward'),
    ('Montecarlo Sommet de Turini', 'MonteCarloS1BolleneCut3Reverse'),
    ('Montecarlo St. Geniez - Sisteron', 'MonteCarloS2SisteronFullReverse'),
    ('Montecarlo Turini - La Bollène-V', 'MonteCarloS1BolleneCut1Reverse'),
    ('Montecarlo Turini - Peïra Cava', 'MonteCarloS1BolleneCut2Forward'),
    ('Montecarlo Turini Descente', 'MonteCarloS1BolleneCut1Reverse'),
    ('Montecarlo Turini Montée', 'MonteCarloS1BolleneCut1Forward'),
    ('Pays de Galles Afon Bidno', 'WelesS4HafrenSouthFullForward'),
    ('Pays de Galles Afon Bidno - Seve', 'WelesS4HafrenSouthFullForward'),
    ('Pays de Galles Afon Biga', 'WelesS3HafrenNorthFullReverse'),
    ('Pays de Galles Afon Biga - Banc ', 'WelesS3HafrenNorthCut2Reverse'),
    ('Pays de Galles Afon Biga - Cwmbi', 'WelesS3HafrenNorthFullReverse'),
    ('Pays de Galles Banc Gwyn', 'WelesS3HafrenNorthCut2Forward'),
    ('Pays de Galles Banc Gwyn - Afon ', 'WelesS3HafrenNorthCut2Forward'),
    ('Pays de Galles Cwmbiga', 'WelesS3HafrenNorthFullForward'),
    ('Pays de Galles Cwmbiga - Afon Bi', 'WelesS3HafrenNorthFullForward'),
    ('Pays de Galles Cwmbiga - Fedw Fa', 'WelesS3HafrenNorthCut1Forward'),
    ('Pays de Galles Fedw Fain', 'WelesS3HafrenNorthCut1Reverse'),
    ('Pays de Galles Fedw Fain - Cwmbi', 'WelesS3HafrenNorthCut1Reverse'),
    ('Pays de Galles Hafren Forest', 'WelesS3HafrenNorthCut1Forward'),
    ('Pays de Galles Ospreys', 'WelesS3HafrenNorthCut2Reverse'),
    ('Pays de Galles Severn', 'WelesS4HafrenSouthFullReverse'),
    ('Pays de Galles Severn - Afon Bid', 'WelesS4HafrenSouthFullReverse'),
    ('Wales Afon Bidno', 'WelesS4HafrenSouthFullForward'),
    ('Wales Afon Bidno - Severn', 'WelesS4HafrenSouthFullForward'),
    ('Wales Afon Bidno – Severn', 'WelesS4HafrenSouthFullForward'),
    ('Wales Afon Biga', 'WelesS3HafrenNorthFullReverse'),
    ('Wales Afon Biga - Banc Gwyn', 'WelesS3HafrenNorthCut2Reverse'),
    ('Wales Afon Biga - Cwmbiga', 'WelesS3HafrenNorthFullReverse'),
    ('Wales Afon Biga – Banc Gwyn', 'WelesS3HafrenNorthCut2Reverse'),
    ('Wales Afon Biga – Cwmbiga', 'WelesS3HafrenNorthFullReverse'),
    ('Wales Banc Gwyn', 'WelesS3HafrenNorthCut2Forward'),
    ('Wales Banc Gwyn - Afon Biga', 'WelesS3HafrenNorthCut2Forward'),
    ('Wales Banc Gwyn – Afon Biga', 'WelesS3HafrenNorthCut2Forward'),
    ('Wales Cwmbiga', 'WelesS3HafrenNorthFullForward'),
    ('Wales Cwmbiga - Afon Biga', 'WelesS3HafrenNorthFullForward'),
    ('Wales Cwmbiga - Fedw Fain', 'WelesS3HafrenNorthCut1Forward'),
    ('Wales Cwmbiga – Afon Biga', 'WelesS3HafrenNorthFullForward'),
    ('Wales Cwmbiga – Fedw Fain', 'WelesS3HafrenNorthCut1Forward'),
    ('Wales Fedw Fain', 'WelesS3HafrenNorthCut1Reverse'),
    ('Wales Fedw Fain - Cwmbiga', 'WelesS3HafrenNorthCut1Reverse'),
    ('Wales Fedw Fain – Cwmbiga', 'WelesS3HafrenNorthCut1Reverse'),
    ('Wales Hafren Forest', 'WelesS3HafrenNorthCut1Forward'),
    ('Wales Ospreys', 'WelesS3HafrenNorthCut2Reverse'),
    ('Wales Severn', 'WelesS4HafrenSouthFullReverse'),
    ('Wales Severn - Afon Bidno', 'WelesS4HafrenSouthFullReverse'),
    ('Wales Severn – Afon Bidno', 'WelesS4HafrenSouthFullReverse'),
    ('WelesS3HafrenNorthCut1Forward', 'WelesS3HafrenNorthCut1Forward'),
    ('WelesS3HafrenNorthCut1Reverse', 'WelesS3HafrenNorthCut1Reverse'),
    ('WelesS3HafrenNorthCut2Forward', 'WelesS3HafrenNorthCut2Forward'),
    ('WelesS3HafrenNorthCut2Reverse', 'WelesS3HafrenNorthCut2Reverse'),
    ('WelesS3HafrenNorthFullForward', 'WelesS3HafrenNorthFullForward'),
    ('WelesS3HafrenNorthFullReverse', 'WelesS3HafrenNorthFullReverse'),
    ('WelesS4HafrenSouthFullForward', 'WelesS4HafrenSouthFullForward'),
    ('WelesS4HafrenSouthFullReverse', 'WelesS4HafrenSouthFullReverse'),
    ('利维尼奥赛道 主赛道', 'LivignoTestTrack01FullForward'),
    ('利维尼奥赛道 主赛道反向', 'LivignoTestTrack01FullReverse'),
    ('利维尼奥赛道 主赛道夜间', 'LivignoTestTrack01FullReverse'),
    ('威尔士 Afon Bidno', 'WelesS4HafrenSouthFullForward'),
    ('威尔士 Afon Bidno - Severn', 'WelesS4HafrenSouthFullForward'),
    ('威尔士 Afon Biga', 'WelesS3HafrenNorthFullReverse'),
    ('威尔士 Afon Biga - Banc Gwyn', 'WelesS3HafrenNorthCut2Reverse'),
    ('威尔士 Afon Biga - Cwmbiga', 'WelesS3HafrenNorthFullReverse'),
    ('威尔士 Banc Gwyn', 'WelesS3HafrenNorthCut2Forward'),
    ('威尔士 Banc Gwyn - Afon Biga', 'WelesS3HafrenNorthCut2Forward'),
    ('威尔士 Cwmbiga', 'WelesS3HafrenNorthFullForward'),
    ('威尔士 Cwmbiga - Afon Biga', 'WelesS3HafrenNorthFullForward'),
    ('威尔士 Cwmbiga - Fedw Fain', 'WelesS3HafrenNorthCut1Forward'),
    ('威尔士 Fedw Fain', 'WelesS3HafrenNorthCut1Reverse'),
    ('威尔士 Fedw Fain - Cwmbiga', 'WelesS3HafrenNorthCut1Reverse'),
    ('威尔士 Ospreys', 'WelesS3HafrenNorthCut2Reverse'),
    ('威尔士 Severn', 'WelesS4HafrenSouthFullReverse'),
    ('威尔士 Severn - Afon Bidno', 'WelesS4HafrenSouthFullReverse'),
    ('威尔士 哈夫伦森林', 'WelesS3HafrenNorthCut1Forward'),
    ('希腊 卢特拉基 - 阿吉伊西奥多里', 'GreeceS4LoutrakiFullForward'),
    ('希腊 埃拉蒂亚', 'GreeceS3ElatiaCut1Forward'),
    ('希腊 埃拉蒂亚 - 泽利', 'GreeceS3ElatiaFullForward'),
    ('希腊 埃拉蒂亚反向', 'GreeceS3ElatiaCut1Reverse'),
    ('希腊 新卢特拉基', 'GreeceS4LoutrakiCut1Forward'),
    ('希腊 新卢特拉基反向', 'GreeceS4LoutrakiCut1Reverse'),
    ('希腊 泽利', 'GreeceS3ElatiaCut2Forward'),
    ('希腊 泽利 - 埃拉蒂亚', 'GreeceS3ElatiaFullReverse'),
    ('希腊 泽利反向', 'GreeceS3ElatiaCut2Reverse'),
    ('希腊 阿吉伊西奥多里', 'GreeceS4LoutrakiCut2Forward'),
    ('希腊 阿吉伊西奥多里 - 卢特拉基', 'GreeceS4LoutrakiFullReverse'),
    ('希腊 阿吉伊西奥多里反向', 'GreeceS4LoutrakiCut2Reverse'),
    ('蒙特卡洛 佩拉卡瓦', 'MonteCarloS1BolleneFullReverse'),
    ('蒙特卡洛 佩拉卡瓦 - 图里尼', 'MonteCarloS1BolleneCut2Reverse'),
    ('蒙特卡洛 佩拉卡瓦 - 拉博莱讷-韦叙比', 'MonteCarloS1BolleneFullReverse'),
    ('蒙特卡洛 图里尼 - 佩拉卡瓦', 'MonteCarloS1BolleneCut2Forward'),
    ('蒙特卡洛 图里尼 - 拉博莱讷-韦叙比', 'MonteCarloS1BolleneCut1Reverse'),
    ('蒙特卡洛 图里尼下山赛', 'MonteCarloS1BolleneCut1Reverse'),
    ('蒙特卡洛 图里尼山顶', 'MonteCarloS1BolleneCut3Reverse'),
    ('蒙特卡洛 图里尼爬山赛', 'MonteCarloS1BolleneCut1Forward'),
    ('蒙特卡洛 圣热尼 - 梅济安', 'MonteCarloS2SisteronCut2Reverse'),
    ('蒙特卡洛 圣热尼 - 锡斯特龙', 'MonteCarloS2SisteronFullReverse'),
    ('蒙特卡洛 拉博莱讷', 'MonteCarloS1BolleneFullForward'),
    ('蒙特卡洛 拉博莱讷-韦叙比 - 佩拉卡瓦', 'MonteCarloS1BolleneFullForward'),
    ('蒙特卡洛 拉博莱讷-韦叙比 - 图里尼', 'MonteCarloS1BolleneCut1Forward'),
    ('蒙特卡洛 普拉阿尔特', 'MonteCarloS1BolleneCut3Forward'),
    ('蒙特卡洛 梅济安 - 圣热尼', 'MonteCarloS2SisteronCut2Forward'),
    ('蒙特卡洛 梅济安 - 锡斯特龙', 'MonteCarloS2SisteronCut1Reverse'),
    ('蒙特卡洛 锡斯特龙 - 圣热尼', 'MonteCarloS2SisteronFullForward'),
    ('蒙特卡洛 锡斯特龙 - 梅济安', 'MonteCarloS2SisteronCut1Forward'),
    ('阿尔萨斯 Mossig 河', 'AlsaceS4SaverneShort1Reverse'),
    ('阿尔萨斯 Obersteigen', 'AlsaceS4SaverneShort1Forward'),
    ('阿尔萨斯 下山赛', 'AlsaceS2MunsterFullReverse'),
    ('阿尔萨斯 吕滕巴赫', 'AlsaceS2MunsterShort1Forward'),
    ('阿尔萨斯 小巴隆', 'AlsaceS2MunsterShort2Reverse'),
    ('阿尔萨斯 小巴隆山口', 'AlsaceS2MunsterShort2Reverse'),
    ('阿尔萨斯 山顶', 'AlsaceS2MunsterShort2Forward'),
    ('阿尔萨斯 施泰因巴赫', 'AlsaceS4SaverneFullReverse'),
    ('阿尔萨斯 明斯特山谷 下山赛', 'AlsaceS2MunsterFullReverse'),
    ('阿尔萨斯 明斯特山谷 爬山赛', 'AlsaceS2MunsterFullForward'),
    ('阿尔萨斯 明斯特山顶 ', 'AlsaceS2MunsterShort2Forward'),
    ('阿尔萨斯 明斯特森林', 'AlsaceS2MunsterShort1Reverse'),
    ('阿尔萨斯 爬山赛', 'AlsaceS2MunsterFullForward'),
    ('阿尔萨斯 穿越 Mossig 河', 'AlsaceS4SaverneShort1Reverse'),
    ('阿尔萨斯 萨韦尔讷森林', 'AlsaceS4SaverneFullForward'),
    ('阿尔萨斯 靠近明斯特的吕滕巴赫', 'AlsaceS2MunsterShort1Forward')
) AS v(alias, variant_raw)
JOIN variant var ON var.raw_name = v.variant_raw
ON CONFLICT (raw_name) DO UPDATE SET
    variant_id = EXCLUDED.variant_id,
    updated_at = now()
WHERE track_alias.variant_id IS NULL;
