version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:
networks:
  default:
    name: veevi