spring:
  application:
    name: racenet-authenticator
  config:
    import: "optional:configserver:"
server:
  port: 8082
selenium:
  url: "http://helper.se-firefox:4444/wd/hub"
racenet-authenticator:
  enable-dirt-rally2: true
  enable-ea-wrc: true