version: '3.5'
services:
  racenet-authenticator:
    build: .
    container_name: racenet-authenticator
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://host.docker.internal:8888
    ports:
      - "8082:8082"
    depends_on:
      - se-firefox
  se-firefox:
    build: firefox
    container_name: se-firefox
    ports:
      - "4444:4444"

networks:
  default:
    name: veevi
    external: true
