version: '3.5'
services:
  fourleft:
    build: .
    container_name: fourleft
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_CLOUD_CONFIG_URI=http://host.docker.internal:8888
    ports:
      - "8081:8081"
    depends_on:
      - db.fourleft
  db.fourleft:
    container_name: db.fourleft
    restart: always
    image: postgres:16
    volumes:
      - /mnt/docker-data/backend-dirtrally2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
networks:
  default:
    name: veevi
    external: true
