version: '3.5'
services:
  backend-wrc:
    build: .
    container_name: backend-wrc
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_CLOUD_CONFIG_URI=http://host.docker.internal:8888
    ports:
      - "8083:8083"
    depends_on:
      - db.backend-wrc
  db.backend-wrc:
    container_name: db.backend-wrc
    image: postgres:15
    volumes:
      - backendwrcdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
networks:
  default:
    name: veevi
volumes:
  backendwrcdata: