-- Token table for the "view/edit this channel's configuration" link generated by the admin-only
-- /fourleft configure edit command. The UUID id is the shareable token; possession of it grants
-- read access to the channel's configuration (mirrors profile_update_request). guild_id/channel_id
-- are Discord snowflakes; the config itself lives in discord_club_configuration, keyed by channel_id.
CREATE TABLE channel_configuration_request
(
    id             UUID NOT NULL,
    guild_id       BIGINT,
    channel_id     BIGINT,
    discord_id     VARCHAR(255),
    requested_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_channelconfigurationrequest PRIMARY KEY (id)
);
